apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: trading-app
type: Opaque
data:
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1oZXJlLWNoYW5nZS1pbi1wcm9kdWN0aW9u  # base64 encoded "your-super-secret-jwt-key-here-change-in-production"
  DB_PASSWORD: cGFzc3dvcmQ=  # base64 encoded "password"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: trading-app
data:
  NODE_ENV: "production"
  PORT: "5000"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "trading_app"
  DB_USER: "postgres"
  JWT_EXPIRES_IN: "7d"
  REDIS_URL: "redis://redis-service:6379"
  UPLOAD_PATH: "./uploads"
  MAX_FILE_SIZE: "5242880"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: trading-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/your-username/trading-app-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: JWT_SECRET
        - name: JWT_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: JWT_EXPIRES_IN
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: REDIS_URL
        - name: UPLOAD_PATH
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: UPLOAD_PATH
        - name: MAX_FILE_SIZE
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: MAX_FILE_SIZE
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: trading-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
